name: riverpod_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  lints: ^2.0.0
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.2
  test: ^1.21.0
